get-AppxPackage *Microsoft.WindowsAlarms* | remove-AppxPackage
get-AppxPackage *Microsoft.WindowsCamera* | remove-AppxPackage
get-AppxPackage *Microsoft.WindowsStore* | remove-AppxPackage
get-AppxPackage *Microsoft.People* | remove-AppxPackage
get-AppxPackage *Microsoft.Messaging* | remove-AppxPackage
get-AppxPackage *Microsoft.MicrosoftStickyNotes* | remove-AppxPackage
get-AppxPackage *Microsoft.WindowsSoundRecorder* | remove-AppxPackage
get-AppxPackage *microsoft.widnowscommunicationsapps* | remove-AppxPackage
get-AppxPackage *Zune* | remove-AppxPackage
get-AppxPackage *WindowsMaps* | remove-AppxPackage
get-AppxPackage *Wallet* | remove-AppxPackage
get-AppxPackage *Office.OneNote* | remove-AppxPackage
get-AppxPackage *Office.OneNote* | remove-AppxPackage
get-AppxPackage *3dViewer* | remove-AppxPackage
get-AppxPackage *Print3D* | remove-AppxPackage
get-AppxPackage *GetHelp* | remove-AppxPackage
get-AppxPackage *Getstarted* | remove-AppxPackage
get-AppxPackage *OfficeHub* | remove-AppxPackage
get-AppxPackage *SkypeApp* | remove-AppxPackage
get-AppxPackage *WindowsFeedbackHub* | remove-AppxPackage
get-AppxPackage *DesktopAppInstaller* | remove-AppxPackage
get-AppxPackage *OneConnect* | remove-AppxPackage
get-AppxPackage *OneConnect* | remove-AppxPackage
get-AppxPackage *People* | remove-AppxPackage
get-AppxPackage *StorePurchaseApp* | remove-AppxPackage
get-AppxPackage *SolitaireCollection* | remove-AppxPackage
get-AppxPackage *Services.Store.Engagement* | remove-AppxPackage
get-AppxPackage *BingWeather* | remove-AppxPackage
get-AppxPackage *Advertising.Xaml* | remove-AppxPackage
get-AppxPackage *Xbox* | remove-AppxPackage
get-AppxPackage *StorePurchaseApp* | remove-AppxPackage
get-AppxPackage *store* | remove-AppxPackage
